name: LeeBurrell
favicon: null
layout_spectrum: 0.19535237387754023
typography_spectrum: 0.5347705567255616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7152028270065784
  lightness: 0.901890829205513
  saturation: 0.3620395746547729
  rhythmicContrast: 0.6262004976160824
purpose: []
