name: LeeBurrell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8093
title: '{Business Development at XPO Logistics + Co-founder of The Gmat Coach + NCAA Official  + World traveler + GT graduate + TED Fan + Guitar player + BMW aficionado + Meditator + Athlete}'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f7fd'
    - '#000000'
    - '#8d7978'
    - '#4d3a34'
    - '#ddc692'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
