name: Lee Burrell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8093
title: '{Business Development at XPO Logistics + Co-founder of The Gmat Coach + NCAA Official  + World traveler + GT graduate + TED Fan + Guitar player + BMW aficionado + Meditator + Athlete}'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#202020'
    - '#a8a8a8'
    - '#d0d0d0'
  brandStrength: 1
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
